if (!require("pacman")) install.packages("pacman")
pacman::p_load(dplyr,
               readr,
               dendextend,
               ggdendro,
               stringr,
               here,
               tidyr,
               tibble,
               broom,
               pryr,
               modelr, 
               magrittr,
               lubridate, 
               ggplot2, 
               plyr, 
               purrr, 
               readxl, 
               ggthemes)

